apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-controller
spec:
  replicas: 2
  selector:
    name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/nginx:alpine
          ports:
            - containerPort: 80
#          volumeMounts:
#            - mountPath: /etc/nginx/nginx.conf
#              name: nginx-config
#              subPath: nginx.conf
#            - mountPath: /home/wwwroot/test
#              name: nginx-data
#      volumes:
#        - name: nginx-config
#          configMap:
#            name: confnginx
#        - name: nginx-data
#          hostPath:
#            path: /home/wwwroot/hello