version: "3.8"
services:
  nginx:
    container_name: nginx-1.21.4
    build:
      context: ""
      dockerfile: Dockerfile
    image: my-nginx:1.21.4
    restart: always
    ports:
      - "80:80"
      - "8101:8101"
    environment:
      TZ: Asia/Shanghai

